minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
blockExoticSubdeps: true
strictDepBuilds: true
dangerouslyAllowAllBuilds: false
trustPolicy: no-downgrade

allowBuilds:
  '@swc/core': true
  core-js: true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
  vue-demi: true

overrides:
  set-cookie-parser: 2.7.2
  'glob@<=11.1.0': '11.1.0'
