[package]
name = "jaredwray/mockhttp"
version = "2.0.0"
description = "MockHTTP test app"
entrypoint = "server"

[dependencies]
"wasmer/edgejs-quickjs" = "=0.2.5"

[fs]
"/app" = "."

[[command]]
name = "server"
module = "wasmer/edgejs-quickjs:edge"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["/app/start.mjs"]
