name: docker-publish

on:
    workflow_dispatch:
    release:
      types: [released]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
         node-version: 22

      # DO NOT USE pnpm here, it will cause issues with Docker build
      - name: Install Dependencies
        run: npm install 

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Build
        run: npm run build

      - name: Set version variable
        run: |
          VERSION=$(node -p 'require("./package.json").version')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image with Version Tag
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jaredwray/mockhttp:${{ env.VERSION }}

      - name: Build and push Docker image as Latest
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jaredwray/mockhttp:latest

      - name: Build Docker Markdown
        run: pnpm docker:readme

        # Update Docker Hub description
      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v2
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         repository: jaredwray/mockhttp
         short-description: ${{ github.event.repository.description }}
         readme-filepath: ./DOCKER.md