name: release

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false
      - run: pnpm install --frozen-lockfile
      - run: pnpm test:ci

  publish:
    name: Publish to npm
    needs: test
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - name: Publish
        run: pnpm publish --provenance --no-git-checks --ignore-scripts
